import { Download, Eye, FileText, Printer } from "lucide-react";
import { useToast } from "../../../store/toast";
import { DashboardDrawer } from "./DashboardWidgets";

export type ReportValue = string | number | boolean | null | undefined;

export type ReportColumn = {
  key: string;
  label: string;
};

export type ReportRow = Record<string, ReportValue>;

export type ReportDefinition = {
  id: string;
  title: string;
  filename: string;
  description: string;
  columns: ReportColumn[];
  rows: ReportRow[];
};

function reportColumnLabel(key: string) {
  return key
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replaceAll("_", " ")
    .replace(/\b\w/g, (letter) => letter.toUpperCase());
}

function toReportValue(value: unknown): ReportValue {
  if (
    value === null ||
    value === undefined ||
    typeof value === "string" ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  if (Array.isArray(value)) return value.join(" · ");
  return String(value);
}

/**
 * Build a report from the same live rows rendered by a dashboard section.
 * Callers can opt into the precise columns appropriate to their active tab.
 */
export function createReport<T extends object>({
  id,
  title,
  filename,
  description,
  rows,
  columns,
}: {
  id: string;
  title: string;
  filename: string;
  description: string;
  rows: readonly T[];
  columns: readonly (keyof T & string)[];
}): ReportDefinition {
  return {
    id,
    title,
    filename,
    description,
    columns: columns.map((key) => ({ key, label: reportColumnLabel(key) })),
    rows: rows.map(
      (row) =>
        Object.fromEntries(
          columns.map((key) => [key, toReportValue(row[key])]),
        ) as ReportRow,
    ),
  };
}

function reportValue(value: ReportValue) {
  if (value === null || value === undefined || value === "") return "—";
  if (typeof value === "boolean") return value ? "Yes" : "No";
  return String(value);
}

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function reportDocument(report: ReportDefinition) {
  const title = escapeHtml(report.title);
  const description = escapeHtml(report.description);
  const heads = report.columns
    .map((column) => `<th>${escapeHtml(column.label)}</th>`)
    .join("");
  const body = report.rows
    .map(
      (row) =>
        `<tr>${report.columns
          .map(
            (column) => `<td>${escapeHtml(reportValue(row[column.key]))}</td>`,
          )
          .join("")}</tr>`,
    )
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${title} — GrowMO</title>
  <style>
    @page { size: auto; margin: 16mm; }
    body { color: darkslategray; font-family: Arial, Helvetica, sans-serif; font-size: 11pt; line-height: 1.4; }
    header { border-bottom: 2px solid seagreen; margin-bottom: 20px; padding-bottom: 12px; }
    .brand { color: forestgreen; font-size: 10pt; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
    h1 { font-family: Georgia, serif; font-size: 24pt; margin: 4px 0; }
    p { color: dimgray; margin: 0; }
    .meta { color: dimgray; font-size: 9pt; margin-top: 12px; }
    table { border-collapse: collapse; width: 100%; }
    th { background: honeydew; color: darkgreen; font-size: 9pt; text-align: left; }
    th, td { border: 1px solid lightgray; padding: 8px; vertical-align: top; }
    tr:nth-child(even) { background: whitesmoke; }
    footer { color: dimgray; font-size: 9pt; margin-top: 20px; }
  </style>
</head>
<body>
  <header>
    <div class="brand">GrowMO farm record</div>
    <h1>${title}</h1>
    <p>${description}</p>
    <div class="meta">Prepared from the live GrowMO dashboard · ${report.rows.length} record${report.rows.length === 1 ? "" : "s"}</div>
  </header>
  <table>
    <thead><tr>${heads}</tr></thead>
    <tbody>${body || `<tr><td colspan="${report.columns.length}">No records are available for this report.</td></tr>`}</tbody>
  </table>
  <footer>Generated by GrowMO. Review this record before sharing it outside your farm team.</footer>
</body>
</html>`;
}

function safeFilename(filename: string) {
  return filename
    .replace(/\.(csv|doc|docx|pdf|html)$/i, "")
    .replace(/[^a-z0-9-_]+/gi, "-")
    .toLowerCase();
}

function previewRowKey(report: ReportDefinition, row: ReportRow) {
  return `${report.id}-${report.columns.map((column) => reportValue(row[column.key])).join("-")}`;
}

export function downloadReportDocument(report: ReportDefinition) {
  const blob = new Blob([reportDocument(report)], {
    type: "application/msword;charset=utf-8",
  });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `${safeFilename(report.filename)}.doc`;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 0);
}

export function printReport(report: ReportDefinition) {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return false;

  printWindow.opener = null;
  printWindow.document.open();
  printWindow.document.write(reportDocument(report));
  printWindow.document.close();
  printWindow.focus();
  window.setTimeout(() => printWindow.print(), 150);
  return true;
}

export function ReportTools({
  report,
  onPreview,
  className = "",
}: {
  report: ReportDefinition;
  onPreview: (report: ReportDefinition) => void;
  className?: string;
}) {
  const toast = useToast();

  return (
    <div
      className={`d-flex flex-wrap align-items-center gap-2 ${className}`.trim()}
    >
      <button
        type="button"
        className="gm-btn gm-btn-soft gm-btn-sm"
        onClick={() => onPreview(report)}
      >
        <Eye /> Preview
      </button>
      <button
        type="button"
        className="gm-btn gm-btn-outline gm-btn-sm"
        onClick={() => {
          if (!printReport(report)) {
            toast.notify(
              "Allow pop-ups to print or save this report as a PDF.",
              "warn",
            );
            return;
          }
          toast.notify(
            "Print preview opened — choose Save as PDF to create a PDF copy.",
            "info",
          );
        }}
      >
        <Printer /> Print / PDF
      </button>
      <button
        type="button"
        className="gm-btn gm-btn-outline gm-btn-sm"
        onClick={() => {
          downloadReportDocument(report);
          toast.notify(
            `${report.title} downloaded as a Word document.`,
            "success",
          );
        }}
      >
        <Download /> Download
      </button>
    </div>
  );
}

export function ReportActionBar({
  report,
  onPreview,
}: {
  report: ReportDefinition;
  onPreview: (report: ReportDefinition) => void;
}) {
  return (
    <section className="gm-card p-3 mt-3">
      <div className="d-flex flex-wrap align-items-center justify-content-between gap-3">
        <div>
          <span className="gm-eyebrow">
            <FileText /> Live report controls
          </span>
          <strong className="d-block mt-1">{report.title}</strong>
          <small className="text-muted">
            {report.rows.length} record{report.rows.length === 1 ? "" : "s"}{" "}
            ready to preview, print or download.
          </small>
        </div>
        <ReportTools report={report} onPreview={onPreview} />
      </div>
    </section>
  );
}

export function ReportPreviewDrawer({
  report,
  onClose,
}: {
  report: ReportDefinition | null;
  onClose: () => void;
}) {
  const toast = useToast();

  return (
    <DashboardDrawer
      open={Boolean(report)}
      title={report ? `${report.title} preview` : "Report preview"}
      onClose={onClose}
      footer={
        report ? (
          <div className="d-grid gap-2">
            <button
              type="button"
              className="gm-btn gm-btn-outline gm-btn-block"
              onClick={() => {
                if (!printReport(report)) {
                  toast.notify(
                    "Allow pop-ups to print or save this report as a PDF.",
                    "warn",
                  );
                  return;
                }
                toast.notify(
                  "Print preview opened — select Save as PDF if you need a PDF file.",
                  "info",
                );
              }}
            >
              <Printer /> Print / save PDF
            </button>
            <button
              type="button"
              className="gm-btn gm-btn-lime gm-btn-block"
              onClick={() => {
                downloadReportDocument(report);
                toast.notify(
                  `${report.title} downloaded as a Word document.`,
                  "success",
                );
              }}
            >
              <Download /> Download document
            </button>
          </div>
        ) : undefined
      }
    >
      {report ? (
        <div>
          <div className="gm-card p-3 mb-3">
            <span className="gm-eyebrow">
              <FileText /> Live data report
            </span>
            <h3 className="font-display mt-2 mb-1">{report.title}</h3>
            <p className="mb-2">{report.description}</p>
            <span className="gm-chip">
              {report.rows.length} record{report.rows.length === 1 ? "" : "s"}{" "}
              included
            </span>
          </div>
          <div className="gm-table-wrap">
            <table className="gm-table">
              <thead>
                <tr>
                  {report.columns.map((column) => (
                    <th key={column.key}>{column.label}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {report.rows.length ? (
                  report.rows.map((row) => (
                    <tr key={previewRowKey(report, row)}>
                      {report.columns.map((column) => (
                        <td key={column.key}>{reportValue(row[column.key])}</td>
                      ))}
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan={report.columns.length}>
                      No records match the current filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      ) : null}
    </DashboardDrawer>
  );
}
