/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCropsRouteImport } from './routes/app/crops'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppInventoryRouteImport } from './routes/app/inventory'
import { Route as AppLabourRouteImport } from './routes/app/labour'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppPlannerRouteImport } from './routes/app/planner'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthAccountStatusRouteImport } from './routes/auth/account-status'
import { Route as AuthHubRouteImport } from './routes/auth/hub'
import { Route as AuthIdentityRouteImport } from './routes/auth/identity'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthPasskeysRouteImport } from './routes/auth/passkeys'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthSecurityRouteImport } from './routes/auth/security'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCropsRoute = AppCropsRouteImport.update({
  id: '/app/crops',
  path: '/app/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/app/inventory',
  path: '/app/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLabourRoute = AppLabourRouteImport.update({
  id: '/app/labour',
  path: '/app/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/app/onboarding',
  path: '/app/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/app/planner',
  path: '/app/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountStatusRoute = AuthAccountStatusRouteImport.update({
  id: '/auth/account-status',
  path: '/auth/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/auth/hub',
  path: '/auth/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdentityRoute = AuthIdentityRouteImport.update({
  id: '/auth/identity',
  path: '/auth/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasskeysRoute = AuthPasskeysRouteImport.update({
  id: '/auth/passkeys',
  path: '/auth/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSecurityRoute = AuthSecurityRouteImport.update({
  id: '/auth/security',
  path: '/auth/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/app/crops': typeof AppCropsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/labour': typeof AppLabourRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/app/crops': typeof AppCropsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/labour': typeof AppLabourRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/app/crops': typeof AppCropsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/labour': typeof AppLabourRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/planner': typeof AppPlannerRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/app/crops'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/labour'
    | '/app/onboarding'
    | '/app/planner'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/services/$slug'
    | '/shop/$slug'
    | '/app/'
    | '/auth/'
    | '/services/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/app/crops'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/labour'
    | '/app/onboarding'
    | '/app/planner'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/services/$slug'
    | '/shop/$slug'
    | '/app'
    | '/auth'
    | '/services'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/app/crops'
    | '/app/dashboard'
    | '/app/inventory'
    | '/app/labour'
    | '/app/onboarding'
    | '/app/planner'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/services/$slug'
    | '/shop/$slug'
    | '/app/'
    | '/auth/'
    | '/services/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AppCropsRoute: typeof AppCropsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppLabourRoute: typeof AppLabourRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AuthAccountStatusRoute: typeof AuthAccountStatusRoute
  AuthHubRoute: typeof AuthHubRoute
  AuthIdentityRoute: typeof AuthIdentityRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthPasskeysRoute: typeof AuthPasskeysRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSecurityRoute: typeof AuthSecurityRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  AppIndexRoute: typeof AppIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/crops': {
      id: '/app/crops'
      path: '/app/crops'
      fullPath: '/app/crops'
      preLoaderRoute: typeof AppCropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/app/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/labour': {
      id: '/app/labour'
      path: '/app/labour'
      fullPath: '/app/labour'
      preLoaderRoute: typeof AppLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/app/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/app/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-status': {
      id: '/auth/account-status'
      path: '/auth/account-status'
      fullPath: '/auth/account-status'
      preLoaderRoute: typeof AuthAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/hub': {
      id: '/auth/hub'
      path: '/auth/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/identity': {
      id: '/auth/identity'
      path: '/auth/identity'
      fullPath: '/auth/identity'
      preLoaderRoute: typeof AuthIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passkeys': {
      id: '/auth/passkeys'
      path: '/auth/passkeys'
      fullPath: '/auth/passkeys'
      preLoaderRoute: typeof AuthPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/security': {
      id: '/auth/security'
      path: '/auth/security'
      fullPath: '/auth/security'
      preLoaderRoute: typeof AuthSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AppCropsRoute: AppCropsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppLabourRoute: AppLabourRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPlannerRoute: AppPlannerRoute,
  AuthAccountStatusRoute: AuthAccountStatusRoute,
  AuthHubRoute: AuthHubRoute,
  AuthIdentityRoute: AuthIdentityRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthPasskeysRoute: AuthPasskeysRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSecurityRoute: AuthSecurityRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  AppIndexRoute: AppIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
