/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthAccountStatusRouteImport } from './routes/auth/account-status'
import { Route as AuthHubRouteImport } from './routes/auth/hub'
import { Route as AuthIdentityRouteImport } from './routes/auth/identity'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthMfaRouteImport } from './routes/auth/mfa'
import { Route as AuthPasskeysRouteImport } from './routes/auth/passkeys'
import { Route as AuthRecoveryRouteImport } from './routes/auth/recovery'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthSecurityRouteImport } from './routes/auth/security'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdvisorRouteImport } from './routes/dashboard/advisor'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardChannelsRouteImport } from './routes/dashboard/channels'
import { Route as DashboardCommunityRouteImport } from './routes/dashboard/community'
import { Route as DashboardCooperativeRouteImport } from './routes/dashboard/cooperative'
import { Route as DashboardCropsRouteImport } from './routes/dashboard/crops'
import { Route as DashboardDashboardRouteImport } from './routes/dashboard/dashboard'
import { Route as DashboardFinanceRouteImport } from './routes/dashboard/finance'
import { Route as DashboardHarvestRouteImport } from './routes/dashboard/harvest'
import { Route as DashboardInventoryRouteImport } from './routes/dashboard/inventory'
import { Route as DashboardLabourRouteImport } from './routes/dashboard/labour'
import { Route as DashboardLogsRouteImport } from './routes/dashboard/logs'
import { Route as DashboardMachineryRouteImport } from './routes/dashboard/machinery'
import { Route as DashboardMapRouteImport } from './routes/dashboard/map'
import { Route as DashboardMarketRouteImport } from './routes/dashboard/market'
import { Route as DashboardNurseryRouteImport } from './routes/dashboard/nursery'
import { Route as DashboardOnboardingRouteImport } from './routes/dashboard/onboarding'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard/orders'
import { Route as DashboardPlannerRouteImport } from './routes/dashboard/planner'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardSeasonsRouteImport } from './routes/dashboard/seasons'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardSoilRouteImport } from './routes/dashboard/soil'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardWalletRouteImport } from './routes/dashboard/wallet'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard/weather'
import { Route as DashboardWeatherProRouteImport } from './routes/dashboard/weather-pro'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as ShopIndexRouteImport } from './routes/shop/index'
import { Route as ShopSlugRouteImport } from './routes/shop/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAccountStatusRoute = AuthAccountStatusRouteImport.update({
  id: '/auth/account-status',
  path: '/auth/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/auth/hub',
  path: '/auth/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIdentityRoute = AuthIdentityRouteImport.update({
  id: '/auth/identity',
  path: '/auth/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMfaRoute = AuthMfaRouteImport.update({
  id: '/auth/mfa',
  path: '/auth/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPasskeysRoute = AuthPasskeysRouteImport.update({
  id: '/auth/passkeys',
  path: '/auth/passkeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRecoveryRoute = AuthRecoveryRouteImport.update({
  id: '/auth/recovery',
  path: '/auth/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSecurityRoute = AuthSecurityRouteImport.update({
  id: '/auth/security',
  path: '/auth/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdvisorRoute = DashboardAdvisorRouteImport.update({
  id: '/dashboard/advisor',
  path: '/dashboard/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/dashboard/analytics',
  path: '/dashboard/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChannelsRoute = DashboardChannelsRouteImport.update({
  id: '/dashboard/channels',
  path: '/dashboard/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCommunityRoute = DashboardCommunityRouteImport.update({
  id: '/dashboard/community',
  path: '/dashboard/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCooperativeRoute = DashboardCooperativeRouteImport.update({
  id: '/dashboard/cooperative',
  path: '/dashboard/cooperative',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCropsRoute = DashboardCropsRouteImport.update({
  id: '/dashboard/crops',
  path: '/dashboard/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardRoute = DashboardDashboardRouteImport.update({
  id: '/dashboard/dashboard',
  path: '/dashboard/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFinanceRoute = DashboardFinanceRouteImport.update({
  id: '/dashboard/finance',
  path: '/dashboard/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHarvestRoute = DashboardHarvestRouteImport.update({
  id: '/dashboard/harvest',
  path: '/dashboard/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/dashboard/inventory',
  path: '/dashboard/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLabourRoute = DashboardLabourRouteImport.update({
  id: '/dashboard/labour',
  path: '/dashboard/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLogsRoute = DashboardLogsRouteImport.update({
  id: '/dashboard/logs',
  path: '/dashboard/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMachineryRoute = DashboardMachineryRouteImport.update({
  id: '/dashboard/machinery',
  path: '/dashboard/machinery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMapRoute = DashboardMapRouteImport.update({
  id: '/dashboard/map',
  path: '/dashboard/map',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/dashboard/market',
  path: '/dashboard/market',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNurseryRoute = DashboardNurseryRouteImport.update({
  id: '/dashboard/nursery',
  path: '/dashboard/nursery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOnboardingRoute = DashboardOnboardingRouteImport.update({
  id: '/dashboard/onboarding',
  path: '/dashboard/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/dashboard/orders',
  path: '/dashboard/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPlannerRoute = DashboardPlannerRouteImport.update({
  id: '/dashboard/planner',
  path: '/dashboard/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/dashboard/records',
  path: '/dashboard/records',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSeasonsRoute = DashboardSeasonsRouteImport.update({
  id: '/dashboard/seasons',
  path: '/dashboard/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSoilRoute = DashboardSoilRouteImport.update({
  id: '/dashboard/soil',
  path: '/dashboard/soil',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/dashboard/team',
  path: '/dashboard/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWalletRoute = DashboardWalletRouteImport.update({
  id: '/dashboard/wallet',
  path: '/dashboard/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/dashboard/weather',
  path: '/dashboard/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWeatherProRoute = DashboardWeatherProRouteImport.update({
  id: '/dashboard/weather-pro',
  path: '/dashboard/weather-pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/cooperative': typeof DashboardCooperativeRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/harvest': typeof DashboardHarvestRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/machinery': typeof DashboardMachineryRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/nursery': typeof DashboardNurseryRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/seasons': typeof DashboardSeasonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/soil': typeof DashboardSoilRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weather-pro': typeof DashboardWeatherProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/cooperative': typeof DashboardCooperativeRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/harvest': typeof DashboardHarvestRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/machinery': typeof DashboardMachineryRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/nursery': typeof DashboardNurseryRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/seasons': typeof DashboardSeasonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/soil': typeof DashboardSoilRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weather-pro': typeof DashboardWeatherProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/auth/account-status': typeof AuthAccountStatusRoute
  '/auth/hub': typeof AuthHubRoute
  '/auth/identity': typeof AuthIdentityRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/mfa': typeof AuthMfaRoute
  '/auth/passkeys': typeof AuthPasskeysRoute
  '/auth/recovery': typeof AuthRecoveryRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/security': typeof AuthSecurityRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/channels': typeof DashboardChannelsRoute
  '/dashboard/community': typeof DashboardCommunityRoute
  '/dashboard/cooperative': typeof DashboardCooperativeRoute
  '/dashboard/crops': typeof DashboardCropsRoute
  '/dashboard/dashboard': typeof DashboardDashboardRoute
  '/dashboard/finance': typeof DashboardFinanceRoute
  '/dashboard/harvest': typeof DashboardHarvestRoute
  '/dashboard/inventory': typeof DashboardInventoryRoute
  '/dashboard/labour': typeof DashboardLabourRoute
  '/dashboard/logs': typeof DashboardLogsRoute
  '/dashboard/machinery': typeof DashboardMachineryRoute
  '/dashboard/map': typeof DashboardMapRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/nursery': typeof DashboardNurseryRoute
  '/dashboard/onboarding': typeof DashboardOnboardingRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/planner': typeof DashboardPlannerRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/seasons': typeof DashboardSeasonsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/soil': typeof DashboardSoilRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/wallet': typeof DashboardWalletRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/weather-pro': typeof DashboardWeatherProRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/dashboard/advisor'
    | '/dashboard/analytics'
    | '/dashboard/channels'
    | '/dashboard/community'
    | '/dashboard/cooperative'
    | '/dashboard/crops'
    | '/dashboard/dashboard'
    | '/dashboard/finance'
    | '/dashboard/harvest'
    | '/dashboard/inventory'
    | '/dashboard/labour'
    | '/dashboard/logs'
    | '/dashboard/machinery'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/nursery'
    | '/dashboard/onboarding'
    | '/dashboard/orders'
    | '/dashboard/planner'
    | '/dashboard/records'
    | '/dashboard/seasons'
    | '/dashboard/settings'
    | '/dashboard/soil'
    | '/dashboard/team'
    | '/dashboard/wallet'
    | '/dashboard/weather'
    | '/dashboard/weather-pro'
    | '/services/$slug'
    | '/shop/$slug'
    | '/auth/'
    | '/dashboard/'
    | '/services/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/dashboard/advisor'
    | '/dashboard/analytics'
    | '/dashboard/channels'
    | '/dashboard/community'
    | '/dashboard/cooperative'
    | '/dashboard/crops'
    | '/dashboard/dashboard'
    | '/dashboard/finance'
    | '/dashboard/harvest'
    | '/dashboard/inventory'
    | '/dashboard/labour'
    | '/dashboard/logs'
    | '/dashboard/machinery'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/nursery'
    | '/dashboard/onboarding'
    | '/dashboard/orders'
    | '/dashboard/planner'
    | '/dashboard/records'
    | '/dashboard/seasons'
    | '/dashboard/settings'
    | '/dashboard/soil'
    | '/dashboard/team'
    | '/dashboard/wallet'
    | '/dashboard/weather'
    | '/dashboard/weather-pro'
    | '/services/$slug'
    | '/shop/$slug'
    | '/auth'
    | '/dashboard'
    | '/services'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/auth/account-status'
    | '/auth/hub'
    | '/auth/identity'
    | '/auth/login'
    | '/auth/mfa'
    | '/auth/passkeys'
    | '/auth/recovery'
    | '/auth/register'
    | '/auth/security'
    | '/dashboard/advisor'
    | '/dashboard/analytics'
    | '/dashboard/channels'
    | '/dashboard/community'
    | '/dashboard/cooperative'
    | '/dashboard/crops'
    | '/dashboard/dashboard'
    | '/dashboard/finance'
    | '/dashboard/harvest'
    | '/dashboard/inventory'
    | '/dashboard/labour'
    | '/dashboard/logs'
    | '/dashboard/machinery'
    | '/dashboard/map'
    | '/dashboard/market'
    | '/dashboard/nursery'
    | '/dashboard/onboarding'
    | '/dashboard/orders'
    | '/dashboard/planner'
    | '/dashboard/records'
    | '/dashboard/seasons'
    | '/dashboard/settings'
    | '/dashboard/soil'
    | '/dashboard/team'
    | '/dashboard/wallet'
    | '/dashboard/weather'
    | '/dashboard/weather-pro'
    | '/services/$slug'
    | '/shop/$slug'
    | '/auth/'
    | '/dashboard/'
    | '/services/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  AuthAccountStatusRoute: typeof AuthAccountStatusRoute
  AuthHubRoute: typeof AuthHubRoute
  AuthIdentityRoute: typeof AuthIdentityRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthMfaRoute: typeof AuthMfaRoute
  AuthPasskeysRoute: typeof AuthPasskeysRoute
  AuthRecoveryRoute: typeof AuthRecoveryRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSecurityRoute: typeof AuthSecurityRoute
  DashboardAdvisorRoute: typeof DashboardAdvisorRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardChannelsRoute: typeof DashboardChannelsRoute
  DashboardCommunityRoute: typeof DashboardCommunityRoute
  DashboardCooperativeRoute: typeof DashboardCooperativeRoute
  DashboardCropsRoute: typeof DashboardCropsRoute
  DashboardDashboardRoute: typeof DashboardDashboardRoute
  DashboardFinanceRoute: typeof DashboardFinanceRoute
  DashboardHarvestRoute: typeof DashboardHarvestRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardLabourRoute: typeof DashboardLabourRoute
  DashboardLogsRoute: typeof DashboardLogsRoute
  DashboardMachineryRoute: typeof DashboardMachineryRoute
  DashboardMapRoute: typeof DashboardMapRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardNurseryRoute: typeof DashboardNurseryRoute
  DashboardOnboardingRoute: typeof DashboardOnboardingRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPlannerRoute: typeof DashboardPlannerRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardSeasonsRoute: typeof DashboardSeasonsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardSoilRoute: typeof DashboardSoilRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardWalletRoute: typeof DashboardWalletRoute
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardWeatherProRoute: typeof DashboardWeatherProRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/account-status': {
      id: '/auth/account-status'
      path: '/auth/account-status'
      fullPath: '/auth/account-status'
      preLoaderRoute: typeof AuthAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/hub': {
      id: '/auth/hub'
      path: '/auth/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/identity': {
      id: '/auth/identity'
      path: '/auth/identity'
      fullPath: '/auth/identity'
      preLoaderRoute: typeof AuthIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mfa': {
      id: '/auth/mfa'
      path: '/auth/mfa'
      fullPath: '/auth/mfa'
      preLoaderRoute: typeof AuthMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passkeys': {
      id: '/auth/passkeys'
      path: '/auth/passkeys'
      fullPath: '/auth/passkeys'
      preLoaderRoute: typeof AuthPasskeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/recovery': {
      id: '/auth/recovery'
      path: '/auth/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/security': {
      id: '/auth/security'
      path: '/auth/security'
      fullPath: '/auth/security'
      preLoaderRoute: typeof AuthSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/advisor': {
      id: '/dashboard/advisor'
      path: '/dashboard/advisor'
      fullPath: '/dashboard/advisor'
      preLoaderRoute: typeof DashboardAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/channels': {
      id: '/dashboard/channels'
      path: '/dashboard/channels'
      fullPath: '/dashboard/channels'
      preLoaderRoute: typeof DashboardChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/community': {
      id: '/dashboard/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof DashboardCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cooperative': {
      id: '/dashboard/cooperative'
      path: '/dashboard/cooperative'
      fullPath: '/dashboard/cooperative'
      preLoaderRoute: typeof DashboardCooperativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/crops': {
      id: '/dashboard/crops'
      path: '/dashboard/crops'
      fullPath: '/dashboard/crops'
      preLoaderRoute: typeof DashboardCropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/dashboard': {
      id: '/dashboard/dashboard'
      path: '/dashboard/dashboard'
      fullPath: '/dashboard/dashboard'
      preLoaderRoute: typeof DashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/finance': {
      id: '/dashboard/finance'
      path: '/dashboard/finance'
      fullPath: '/dashboard/finance'
      preLoaderRoute: typeof DashboardFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/harvest': {
      id: '/dashboard/harvest'
      path: '/dashboard/harvest'
      fullPath: '/dashboard/harvest'
      preLoaderRoute: typeof DashboardHarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/inventory': {
      id: '/dashboard/inventory'
      path: '/dashboard/inventory'
      fullPath: '/dashboard/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/labour': {
      id: '/dashboard/labour'
      path: '/dashboard/labour'
      fullPath: '/dashboard/labour'
      preLoaderRoute: typeof DashboardLabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/logs': {
      id: '/dashboard/logs'
      path: '/dashboard/logs'
      fullPath: '/dashboard/logs'
      preLoaderRoute: typeof DashboardLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/machinery': {
      id: '/dashboard/machinery'
      path: '/dashboard/machinery'
      fullPath: '/dashboard/machinery'
      preLoaderRoute: typeof DashboardMachineryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/map': {
      id: '/dashboard/map'
      path: '/dashboard/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof DashboardMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/market': {
      id: '/dashboard/market'
      path: '/dashboard/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/nursery': {
      id: '/dashboard/nursery'
      path: '/dashboard/nursery'
      fullPath: '/dashboard/nursery'
      preLoaderRoute: typeof DashboardNurseryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/onboarding': {
      id: '/dashboard/onboarding'
      path: '/dashboard/onboarding'
      fullPath: '/dashboard/onboarding'
      preLoaderRoute: typeof DashboardOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/planner': {
      id: '/dashboard/planner'
      path: '/dashboard/planner'
      fullPath: '/dashboard/planner'
      preLoaderRoute: typeof DashboardPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/dashboard/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/seasons': {
      id: '/dashboard/seasons'
      path: '/dashboard/seasons'
      fullPath: '/dashboard/seasons'
      preLoaderRoute: typeof DashboardSeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/soil': {
      id: '/dashboard/soil'
      path: '/dashboard/soil'
      fullPath: '/dashboard/soil'
      preLoaderRoute: typeof DashboardSoilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/dashboard/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/wallet': {
      id: '/dashboard/wallet'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/dashboard/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/weather-pro': {
      id: '/dashboard/weather-pro'
      path: '/dashboard/weather-pro'
      fullPath: '/dashboard/weather-pro'
      preLoaderRoute: typeof DashboardWeatherProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  AuthAccountStatusRoute: AuthAccountStatusRoute,
  AuthHubRoute: AuthHubRoute,
  AuthIdentityRoute: AuthIdentityRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthMfaRoute: AuthMfaRoute,
  AuthPasskeysRoute: AuthPasskeysRoute,
  AuthRecoveryRoute: AuthRecoveryRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSecurityRoute: AuthSecurityRoute,
  DashboardAdvisorRoute: DashboardAdvisorRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardChannelsRoute: DashboardChannelsRoute,
  DashboardCommunityRoute: DashboardCommunityRoute,
  DashboardCooperativeRoute: DashboardCooperativeRoute,
  DashboardCropsRoute: DashboardCropsRoute,
  DashboardDashboardRoute: DashboardDashboardRoute,
  DashboardFinanceRoute: DashboardFinanceRoute,
  DashboardHarvestRoute: DashboardHarvestRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardLabourRoute: DashboardLabourRoute,
  DashboardLogsRoute: DashboardLogsRoute,
  DashboardMachineryRoute: DashboardMachineryRoute,
  DashboardMapRoute: DashboardMapRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardNurseryRoute: DashboardNurseryRoute,
  DashboardOnboardingRoute: DashboardOnboardingRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPlannerRoute: DashboardPlannerRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardSeasonsRoute: DashboardSeasonsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSoilRoute: DashboardSoilRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardWalletRoute: DashboardWalletRoute,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardWeatherProRoute: DashboardWeatherProRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
